[{
    "_fstchid": 1,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 0,
    "_pid": null,
    "_depth": 0,
    "tag": "root",
    "expanded": true,
    "display": false,
    "checked": false,
    "_conns": [],
    "conns": []
}, {
    "_fstchid": 2,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 1,
    "_pid": 0,
    "_depth": 1,
    "tag": "html",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["l"],
    "conns": []
}, {
    "_fstchid": 3,
    "_lsibid": null,
    "_rsibid": 5,
    "_id": 2,
    "_pid": 1,
    "_depth": 2,
    "tag": "head",
    "expanded": false,
    "display": true,
    "checked": false,
    "_conns": ["ws", "t"],
    "conns": ["t"]
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 4,
    "_id": 3,
    "_pid": 2,
    "_depth": 3,
    "tag": "link",
    "expanded": true,
    "display": false,
    "checked": false,
    "_conns": ["ws", "ws", "t"],
    "conns": ["ws", "t"]
}, {
    "_fstchid": null,
    "_lsibid": 3,
    "_rsibid": null,
    "_id": 4,
    "_depth": 3,
    "tag": "link",
    "expanded": true,
    "display": false,
    "checked": false,
    "_conns": ["ws", "ws", "l"],
    "conns": ["ws", "l"]
}, {
    "_fstchid": 10,
    "_lsibid": 2,
    "_rsibid": null,
    "_id": 5,
    "_depth": 2,
    "tag": "body",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "l"],
    "conns": ["l"]
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 7,
    "_id": 10,
    "_pid": 5,
    "_depth": 3,
    "tag": "a",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "t"],
    "conns": ["ws", "t"]
}, {
    "_fstchid": 11,
    "_lsibid": 10,
    "_rsibid": 8,
    "_id": 7,
    "_depth": 3,
    "tag": "div",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "t"],
    "conns": ["ws", "t"]
}, {
    "_fstchid": 12,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 11,
    "_pid": 7,
    "_depth": 4,
    "tag": "ul",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "v", "l"],
    "conns": ["ws", "v", "l"]
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 12,
    "_pid": 11,
    "_depth": 5,
    "tag": "li",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "v", "ws", "l"],
    "conns": ["ws", "v", "ws", "l"]
}, {
    "_fstchid": null,
    "_lsibid": 7,
    "_rsibid": 9,
    "_id": 8,
    "_depth": 3,
    "tag": "div",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "t"],
    "conns": ["ws", "t"]
}, {
    "_fstchid": null,
    "_lsibid": 8,
    "_rsibid": null,
    "_id": 9,
    "_depth": 3,
    "tag": "div",
    "expanded": true,
    "display": true,
    "checked": false,
    "_conns": ["ws", "ws", "l"],
    "conns": ["ws", "l"]
}]