[{
    "_fstchid": 53,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 52,
    "_pid": null,
    "_depth": 0,
    "text": "root",
    "expanded": true,
    "display": false,
    "type": "root"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 54,
    "_id": 53,
    "_pid": 52,
    "_depth": 1,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 56,
    "_lsibid": 53,
    "_rsibid": 55,
    "_id": 54,
    "_depth": 1,
    "text": "db1",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 57,
    "_id": 56,
    "_pid": 54,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 59,
    "_lsibid": 56,
    "_rsibid": 58,
    "_id": 57,
    "_depth": 2,
    "text": "db2",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 59,
    "_pid": 57,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 57,
    "_rsibid": 60,
    "_id": 58,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 62,
    "_lsibid": 58,
    "_rsibid": 61,
    "_id": 60,
    "_depth": 2,
    "text": "db3",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 63,
    "_id": 62,
    "_pid": 60,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 65,
    "_lsibid": 62,
    "_rsibid": 64,
    "_id": 63,
    "_depth": 3,
    "text": "db4",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 65,
    "_pid": 63,
    "_depth": 4,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 63,
    "_rsibid": 66,
    "_id": 64,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 68,
    "_lsibid": 64,
    "_rsibid": 67,
    "_id": 66,
    "_depth": 3,
    "text": "db5",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 68,
    "_pid": 66,
    "_depth": 4,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 66,
    "_rsibid": null,
    "_id": 67,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 60,
    "_rsibid": null,
    "_id": 61,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 54,
    "_rsibid": 69,
    "_id": 55,
    "_depth": 1,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 71,
    "_lsibid": 55,
    "_rsibid": 70,
    "_id": 69,
    "_depth": 1,
    "text": "db6",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": 72,
    "_id": 71,
    "_pid": 69,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 74,
    "_lsibid": 71,
    "_rsibid": 73,
    "_id": 72,
    "_depth": 2,
    "text": "db7",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 74,
    "_pid": 72,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 72,
    "_rsibid": 75,
    "_id": 73,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 77,
    "_lsibid": 73,
    "_rsibid": 76,
    "_id": 75,
    "_depth": 2,
    "text": "db8",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 77,
    "_pid": 75,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 75,
    "_rsibid": 78,
    "_id": 76,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": 80,
    "_lsibid": 76,
    "_rsibid": 79,
    "_id": 78,
    "_depth": 2,
    "text": "db9",
    "expanded": true,
    "display": true,
    "type": "index"
}, {
    "_fstchid": null,
    "_lsibid": null,
    "_rsibid": null,
    "_id": 80,
    "_pid": 78,
    "_depth": 3,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 78,
    "_rsibid": null,
    "_id": 79,
    "_depth": 2,
    "text": "+",
    "display": true,
    "type": "plus"
}, {
    "_fstchid": null,
    "_lsibid": 69,
    "_rsibid": null,
    "_id": 70,
    "_depth": 1,
    "text": "+",
    "display": true,
    "type": "plus"
}]